// crmmarkeechat/mockData.ts — dữ liệu mẫu cục bộ để xem UI, không gọi API thật.

import type { AssigneeOption, CrmDeal, StageHistoryEntry } from "./types";

export const MOCK_ASSIGNEES: AssigneeOption[] = [
  { id: "u1", name: "Nguyễn Văn An" },
  { id: "u2", name: "Trần Thị Bình" },
  { id: "u3", name: "Lê Hoàng Cường" },
  { id: "u4", name: "Phạm Thu Dung" },
  { id: "u5", name: "Hoàng Minh Đức" },
];

function assigneeName(id?: string): string | undefined {
  return MOCK_ASSIGNEES.find((a) => a.id === id)?.name;
}

function history(entries: Array<Partial<StageHistoryEntry>>): StageHistoryEntry[] {
  return entries.map((e, i) => ({
    id: e.id || `h${i}`,
    created_at: e.created_at || "2026-06-01T08:00:00.000Z",
    actor: e.actor,
    from_stage: e.from_stage,
    to_stage: e.to_stage,
    action: e.action,
    note: e.note,
  }));
}

const RAW_DEALS: Array<Omit<CrmDeal, "lead_name" | "sdr_name" | "is_assigned">> = [
  {
    id: "d1",
    customer_name: "Công ty TNHH Minh Phát",
    company_name: "Minh Phát Co.,Ltd",
    phone: "0901234567",
    email: "contact@minhphat.vn",
    city: "TP. Hồ Chí Minh",
    industry: "Bán lẻ",
    source_platform: "Facebook",
    deal_stage: "new_lead",
    priority: "medium",
    days_in_stage: 1,
    leaded_by: "u1",
    sdr_id: "u2",
    created_at: "2026-07-08T02:00:00.000Z",
    stage_history: history([{ id: "d1h1", created_at: "2026-07-08T02:00:00.000Z", action: "created", to_stage: "new_lead" }]),
  },
  {
    id: "d2",
    customer_name: "Cửa hàng Thời trang Xuân Mai",
    company_name: "Xuân Mai Fashion",
    phone: "0912345678",
    email: "xuanmai.fashion@gmail.com",
    city: "Hà Nội",
    industry: "Bán lẻ",
    source_platform: "Zalo",
    deal_stage: "new_lead",
    priority: "low",
    days_in_stage: 3,
    leaded_by: "u3",
    created_at: "2026-07-06T02:00:00.000Z",
    stage_history: history([{ id: "d2h1", created_at: "2026-07-06T02:00:00.000Z", action: "created", to_stage: "new_lead" }]),
  },
  {
    id: "d3",
    customer_name: "Nhà hàng Hải Sản Biển Xanh",
    company_name: "Biển Xanh Restaurant",
    phone: "0923456789",
    email: "bienxanh@restaurant.vn",
    city: "Đà Nẵng",
    industry: "F&B",
    source_platform: "Website",
    deal_stage: "contacted",
    priority: "medium",
    days_in_stage: 2,
    decision_maker: "Chị Hương (Quản lý)",
    leaded_by: "u2",
    sdr_id: "u1",
    created_at: "2026-07-05T02:00:00.000Z",
    stage_history: history([
      { id: "d3h1", created_at: "2026-07-05T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d3h2", created_at: "2026-07-07T04:00:00.000Z", actor: "Trần Thị Bình", from_stage: "new_lead", to_stage: "contacted", note: "Đã gọi điện tư vấn ban đầu." },
    ]),
  },
  {
    id: "d4",
    customer_name: "Trung tâm Anh ngữ Bright Future",
    company_name: "Bright Future English Center",
    phone: "0934567890",
    email: "info@brightfuture.edu.vn",
    website: "brightfuture.edu.vn",
    city: "TP. Hồ Chí Minh",
    industry: "Giáo dục",
    source_platform: "Referral",
    deal_stage: "qualified",
    priority: "high",
    days_in_stage: 4,
    decision_maker: "Anh Tuấn (Giám đốc)",
    leaded_by: "u4",
    sdr_id: "u3",
    created_at: "2026-06-29T02:00:00.000Z",
    stage_history: history([
      { id: "d4h1", created_at: "2026-06-29T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d4h2", created_at: "2026-07-01T03:00:00.000Z", actor: "Phạm Thu Dung", from_stage: "new_lead", to_stage: "contacted" },
      { id: "d4h3", created_at: "2026-07-03T03:00:00.000Z", actor: "Phạm Thu Dung", from_stage: "contacted", to_stage: "qualified", note: "Xác nhận có nhu cầu triển khai trong quý này." },
    ]),
  },
  {
    id: "d5",
    customer_name: "Khách sạn Ánh Dương",
    company_name: "Ánh Dương Hotel",
    phone: "0945678901",
    email: "booking@anhduonghotel.vn",
    city: "Nha Trang",
    industry: "Du lịch",
    source_platform: "Event",
    deal_stage: "requirement",
    priority: "medium",
    days_in_stage: 2,
    decision_maker: "Chị Lan (Chủ khách sạn)",
    note: "Cần tích hợp với hệ thống booking hiện tại.",
    leaded_by: "u1",
    sdr_id: "u4",
    created_at: "2026-06-27T02:00:00.000Z",
    stage_history: history([
      { id: "d5h1", created_at: "2026-06-27T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d5h2", created_at: "2026-07-02T03:00:00.000Z", from_stage: "new_lead", to_stage: "requirement", note: "Ghi nhận yêu cầu tích hợp booking." },
    ]),
  },
  {
    id: "d6",
    customer_name: "Công ty CP Vận tải Phú Cường",
    company_name: "Phú Cường Logistics",
    phone: "0956789012",
    email: "sales@phucuonglog.vn",
    tax_code: "0301234567",
    city: "Bình Dương",
    industry: "Logistics",
    source_platform: "Hotline",
    deal_stage: "proposal_sent",
    priority: "high",
    estimated_budget: 45000000,
    decision_maker: "Anh Cường (Tổng giám đốc)",
    last_attachment_name: "Baogia_PhuCuong_v2.pdf",
    last_attachment_url: "https://files.example.com/baogia_phucuong_v2.pdf",
    leaded_by: "u5",
    sdr_id: "u2",
    created_at: "2026-06-20T02:00:00.000Z",
    stage_history: history([
      { id: "d6h1", created_at: "2026-06-20T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d6h2", created_at: "2026-06-24T03:00:00.000Z", from_stage: "qualified", to_stage: "requirement" },
      { id: "d6h3", created_at: "2026-06-29T03:00:00.000Z", actor: "Hoàng Minh Đức", from_stage: "requirement", to_stage: "proposal_sent", note: "Đã gửi báo giá gói Enterprise." },
    ]),
  },
  {
    id: "d7",
    customer_name: "Phòng khám Đa khoa Tâm An",
    company_name: "Tâm An Clinic",
    phone: "0967890123",
    email: "lienhe@tamanclinic.vn",
    city: "TP. Hồ Chí Minh",
    industry: "Y tế",
    source_platform: "Website",
    deal_stage: "proposal_sent",
    priority: "medium",
    estimated_budget: 28000000,
    decision_maker: "BS. Minh (Giám đốc phòng khám)",
    last_attachment_name: "Proposal_TamAn.pdf",
    last_attachment_url: "https://files.example.com/proposal_taman.pdf",
    leaded_by: "u2",
    created_at: "2026-06-22T02:00:00.000Z",
    stage_history: history([
      { id: "d7h1", created_at: "2026-06-22T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d7h2", created_at: "2026-06-28T03:00:00.000Z", from_stage: "requirement", to_stage: "proposal_sent" },
    ]),
  },
  {
    id: "d8",
    customer_name: "Chuỗi Cà phê Note Coffee",
    company_name: "Note Coffee Group",
    phone: "0978901234",
    email: "hello@notecoffee.vn",
    city: "Hà Nội",
    industry: "F&B",
    source_platform: "Manual",
    deal_stage: "negotiation",
    priority: "high",
    estimated_budget: 60000000,
    decision_maker: "Chị Ngọc (CEO)",
    leaded_by: "u3",
    sdr_id: "u5",
    created_at: "2026-06-15T02:00:00.000Z",
    stage_history: history([
      { id: "d8h1", created_at: "2026-06-15T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d8h2", created_at: "2026-06-25T03:00:00.000Z", from_stage: "proposal_sent", to_stage: "negotiation", note: "Đàm phán lại mức giá do triển khai 12 chi nhánh." },
    ]),
  },
  {
    id: "d9",
    customer_name: "Siêu thị điện máy Việt Phát",
    company_name: "Việt Phát Electronics",
    phone: "0989012345",
    email: "kinhdoanh@vietphat.vn",
    tax_code: "0308765432",
    city: "Cần Thơ",
    industry: "Bán lẻ",
    source_platform: "Referral",
    deal_stage: "contract_sent",
    priority: "urgent",
    estimated_budget: 120000000,
    decision_maker: "Anh Phát (Chủ chuỗi cửa hàng)",
    last_attachment_name: "HopDong_VietPhat_final.pdf",
    last_attachment_url: "https://files.example.com/hopdong_vietphat.pdf",
    contract_status: "pending",
    leaded_by: "u4",
    sdr_id: "u1",
    created_at: "2026-06-10T02:00:00.000Z",
    stage_history: history([
      { id: "d9h1", created_at: "2026-06-10T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d9h2", created_at: "2026-06-30T03:00:00.000Z", from_stage: "negotiation", to_stage: "contract_sent", note: "Đã gửi hợp đồng bản cuối, chờ ký." },
    ]),
  },
  {
    id: "d10",
    customer_name: "Công ty Xây dựng Đại Thành",
    company_name: "Đại Thành Construction",
    phone: "0990123456",
    email: "info@daithanh-xd.vn",
    tax_code: "0312345678",
    city: "Hải Phòng",
    industry: "Xây dựng",
    source_platform: "Hotline",
    deal_stage: "won",
    priority: "high",
    estimated_budget: 95000000,
    decision_maker: "Anh Thành (Giám đốc)",
    last_attachment_name: "HopDong_DaiThanh_signed.pdf",
    last_attachment_url: "https://files.example.com/hopdong_daithanh.pdf",
    contract_status: "signed",
    closed_at: "2026-07-01T04:00:00.000Z",
    warranty_expires_at: "2027-07-01",
    leaded_by: "u1",
    sdr_id: "u3",
    created_at: "2026-05-20T02:00:00.000Z",
    stage_history: history([
      { id: "d10h1", created_at: "2026-05-20T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d10h2", created_at: "2026-06-15T03:00:00.000Z", from_stage: "contract_sent", to_stage: "won", note: "Khách đã ký hợp đồng và thanh toán đợt 1." },
    ]),
  },
  {
    id: "d11",
    customer_name: "Trường Mầm non Hoa Sen",
    company_name: "Hoa Sen Kindergarten",
    phone: "0901112233",
    email: "hoasenkindergarten@gmail.com",
    city: "TP. Hồ Chí Minh",
    industry: "Giáo dục",
    source_platform: "Website",
    deal_stage: "won",
    priority: "medium",
    estimated_budget: 32000000,
    decision_maker: "Cô Mai (Hiệu trưởng)",
    contract_status: "completed",
    closed_at: "2026-06-20T04:00:00.000Z",
    warranty_expires_at: "2027-06-20",
    leaded_by: "u2",
    created_at: "2026-05-10T02:00:00.000Z",
    stage_history: history([
      { id: "d11h1", created_at: "2026-05-10T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d11h2", created_at: "2026-06-05T03:00:00.000Z", from_stage: "contract_sent", to_stage: "won" },
    ]),
  },
  {
    id: "d12",
    customer_name: "Cửa hàng Mỹ phẩm Sắc Xinh",
    company_name: "Sắc Xinh Cosmetics",
    phone: "0912223344",
    email: "sacxinh.cosmetics@gmail.com",
    city: "Vũng Tàu",
    industry: "Bán lẻ",
    source_platform: "Facebook",
    deal_stage: "lost",
    priority: "low",
    estimated_budget: 15000000,
    reject_reason_type: "Gia",
    reject_reason_text: "Ngân sách không đủ trong quý này.",
    reject_reason: "Ngân sách không đủ trong quý này.",
    closed_at: "2026-06-18T04:00:00.000Z",
    leaded_by: "u3",
    created_at: "2026-05-25T02:00:00.000Z",
    stage_history: history([
      { id: "d12h1", created_at: "2026-05-25T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d12h2", created_at: "2026-06-18T04:00:00.000Z", from_stage: "negotiation", to_stage: "lost", note: "Khách từ chối do giá." },
    ]),
  },
  {
    id: "d13",
    customer_name: "Gara Ô tô Thành Đạt",
    company_name: "Thành Đạt Auto",
    phone: "0923334455",
    email: "thanhdatauto@gmail.com",
    city: "Đồng Nai",
    industry: "Khác",
    source_platform: "Manual",
    deal_stage: "lost",
    priority: "medium",
    reject_reason_type: "DoiThu",
    reject_reason_text: "Đã chọn giải pháp của đối thủ.",
    reject_reason: "Đã chọn giải pháp của đối thủ.",
    closed_at: "2026-06-12T04:00:00.000Z",
    leaded_by: "u5",
    created_at: "2026-05-18T02:00:00.000Z",
    stage_history: history([
      { id: "d13h1", created_at: "2026-05-18T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d13h2", created_at: "2026-06-12T04:00:00.000Z", from_stage: "proposal_sent", to_stage: "lost" },
    ]),
  },
  {
    id: "d14",
    customer_name: "Công ty TM Bình Minh",
    company_name: "Bình Minh Trading",
    phone: "0934445566",
    email: "binhminh.trading@gmail.com",
    city: "Long An",
    industry: "Thương mại điện tử",
    source_platform: "Zalo",
    deal_stage: "on_hold",
    priority: "medium",
    estimated_budget: 20000000,
    note: "Khách xin tạm hoãn 1 tháng do đang tái cơ cấu nhân sự.",
    follow_up_date: "2026-08-01T02:00:00.000Z",
    leaded_by: "u4",
    sdr_id: "u2",
    created_at: "2026-06-01T02:00:00.000Z",
    stage_history: history([
      { id: "d14h1", created_at: "2026-06-01T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d14h2", created_at: "2026-06-25T03:00:00.000Z", from_stage: "qualified", to_stage: "on_hold", note: "Tạm hoãn theo yêu cầu khách." },
    ]),
  },
  {
    id: "d15",
    customer_name: "Nha khoa Sài Gòn Smile",
    company_name: "Sài Gòn Smile Dental",
    phone: "0945556677",
    email: "contact@saigonsmile.vn",
    city: "TP. Hồ Chí Minh",
    industry: "Y tế",
    source_platform: "Event",
    deal_stage: "on_hold",
    priority: "low",
    estimated_budget: 18000000,
    note: "Chờ ngân sách năm tài chính mới.",
    follow_up_date: "2026-09-15T02:00:00.000Z",
    leaded_by: "u1",
    created_at: "2026-06-05T02:00:00.000Z",
    stage_history: history([
      { id: "d15h1", created_at: "2026-06-05T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d15h2", created_at: "2026-06-28T03:00:00.000Z", from_stage: "requirement", to_stage: "on_hold" },
    ]),
  },
  {
    id: "d16",
    customer_name: "Chuỗi Nhà sách Tri Thức Việt",
    company_name: "Tri Thức Việt Bookstore",
    phone: "0956667788",
    email: "trithucviet.bookstore@gmail.com",
    city: "Huế",
    industry: "Bán lẻ",
    source_platform: "Website",
    deal_stage: "contacted",
    priority: "low",
    days_in_stage: 5,
    decision_maker: "Chị Yến (Quản lý chuỗi)",
    leaded_by: "u2",
    created_at: "2026-06-30T02:00:00.000Z",
    stage_history: history([
      { id: "d16h1", created_at: "2026-06-30T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d16h2", created_at: "2026-07-02T03:00:00.000Z", from_stage: "new_lead", to_stage: "contacted" },
    ]),
  },
  {
    id: "d17",
    customer_name: "Spa & Clinic Ngọc Trai",
    company_name: "Ngọc Trai Spa",
    phone: "0967778899",
    email: "ngoctraispa@gmail.com",
    city: "Nha Trang",
    industry: "Khác",
    source_platform: "Facebook",
    deal_stage: "qualified",
    priority: "medium",
    days_in_stage: 1,
    decision_maker: "Chị Trai (Chủ spa)",
    leaded_by: "u5",
    sdr_id: "u4",
    created_at: "2026-07-04T02:00:00.000Z",
    stage_history: history([
      { id: "d17h1", created_at: "2026-07-04T02:00:00.000Z", action: "created", to_stage: "new_lead" },
      { id: "d17h2", created_at: "2026-07-06T03:00:00.000Z", from_stage: "contacted", to_stage: "qualified" },
    ]),
  },
];

export const MOCK_DEALS: CrmDeal[] = RAW_DEALS.map((deal) => ({
  ...deal,
  lead_name: assigneeName(deal.leaded_by),
  sdr_name: assigneeName(deal.sdr_id),
  is_assigned: Boolean(deal.sdr_id),
}));
