#!/bin/bash
cd /opt/apps/seeding_markeeai/scraper-linkedin

echo "=== Resolving ZCA/Zalo files with THEIRS (origin/feature/zalo-restyle-form-v2) ==="

git checkout --theirs linkedin_group_crawler/package.json && git add linkedin_group_crawler/package.json && echo "OK: package.json"
git checkout --theirs linkedin_group_crawler/package-lock.json && git add linkedin_group_crawler/package-lock.json && echo "OK: package-lock.json"
git checkout --theirs linkedin_group_crawler/scripts/zca_api_bridge.js && git add linkedin_group_crawler/scripts/zca_api_bridge.js && echo "OK: zca_api_bridge.js"
git checkout --theirs linkedin_group_crawler/scripts/zca_persistent_listener.js && git add linkedin_group_crawler/scripts/zca_persistent_listener.js && echo "OK: zca_persistent_listener.js"
git checkout --theirs linkedin_group_crawler/test_zca.py && git add linkedin_group_crawler/test_zca.py && echo "OK: test_zca.py"

echo "=== Resolving zalo routes with THEIRS ==="
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/accounts.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/accounts.py && echo "OK: accounts.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/auth.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/auth.py && echo "OK: auth.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/broadcasts.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/broadcasts.py && echo "OK: broadcasts.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/conversations.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/conversations.py && echo "OK: conversations.py"
git checkout --theuits linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/crawler.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/crawler.py && echo "OK: crawler.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/events.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/events.py && echo "OK: events.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/inbox_share.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/api/routes/inbox_share.py && echo "OK: inbox_share.py"

echo "=== Resolving zalo services with THEIRS ==="
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_api_bridge.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_api_bridge.py && echo "OK: zca_api_bridge.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_broadcast_sender.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_broadcast_sender.py && echo "OK: zca_broadcast_sender.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_persistent_listener.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_persistent_listener.py && echo "OK: zca_persistent_listener.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_qr_bridge.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/services/zca_qr_bridge.py && echo "OK: zca_qr_bridge.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/services/supabase_service.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/services/supabase_service.py && echo "OK: supabase_service.py"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/zalo/config.py && git add linkedin_group_crawler/app/modules/all_platform/zalo/config.py && echo "OK: config.py"

echo "=== Resolving shared all_platform files with OURS (keep current) ==="
git checkout --ours linkedin_group_crawler/app/modules/all_platform/routers/crawl_facebook.py && git add linkedin_group_crawler/app/modules/all_platform/routers/crawl_facebook.py && echo "OK: crawl_facebook.py (ours)"
git checkout --ours linkedin_group_crawler/app/modules/facebook/src/modules/crawl_fb/schemas/crawl_schema.py && git add linkedin_group_crawler/app/modules/facebook/src/modules/crawl_fb/schemas/crawl_schema.py && echo "OK: crawl_schema.py (ours)"
git checkout --ours linkedin_group_crawler/app/modules/facebook/src/storages/sessions/default_account_cookie.json && git add linkedin_group_crawler/app/modules/facebook/src/storages/sessions/default_account_cookie.json && echo "OK: default_account_cookie.json (ours)"
git checkout --ours linkedin_group_crawler/app/modules/all_platform/routers/fb.py && git add linkedin_group_crawler/app/modules/all_platform/routers/fb.py && echo "OK: fb.py (ours)"
git checkout --ours linkedin_group_crawler/app/modules/all_platform/routers/groups.py && git add linkedin_group_crawler/app/modules/all_platform/routers/groups.py && echo "OK: groups.py (ours)"

echo "=== Resolving UI files: Zalo-related with THEIRS, Facebook login with OURS ==="
git checkout --theirs linkedin-crawler-ui/services/zaloCrawlerService.ts && git add linkedin-crawler-ui/services/zaloCrawlerService.ts && echo "OK: zaloCrawlerService.ts (theirs)"
git checkout --theirs linkedin-crawler-ui/services/zaloExtension.ts && git add linkedin-crawler-ui/services/zaloExtension.ts && echo "OK: zaloExtension.ts (theirs)"
git checkout --theirs linkedin-crawler-ui/types/zalo-api.ts && git add linkedin-crawler-ui/types/zalo-api.ts && echo "OK: zalo-api.ts (theirs)"
git checkout --theirs linkedin-crawler-ui/hooks/useZaloCrawlerFlow.ts && git add linkedin-crawler-ui/hooks/useZaloCrawlerFlow.ts && echo "OK: useZaloCrawlerFlow.ts (theirs)"
git checkout --theirs linkedin-crawler-ui/contexts/AppAuthContext.tsx && git add linkedin-crawler-ui/contexts/AppAuthContext.tsx && echo "OK: AppAuthContext.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloChatView.tsx && git add linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloChatView.tsx && echo "OK: ZaloChatView.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloInboxMonitorPanel.tsx && git add linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloInboxMonitorPanel.tsx && echo "OK: ZaloInboxMonitorPanel.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloAccountManagerPanel.tsx && git add linkedin-crawler-ui/components/all-platform/zalo/dashboard/ZaloAccountManagerPanel.tsx && echo "OK: ZaloAccountManagerPanel.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/zalo/dashboard/sidebar/ZaloConversationListVirtualized.tsx && git add linkedin-crawler-ui/components/all-platform/zalo/dashboard/sidebar/ZaloConversationListVirtualized.tsx && echo "OK: ZaloConversationListVirtualized.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/zalo/dashboard/chat/ZaloEmptyChat.tsx && git add linkedin-crawler-ui/components/all-platform/zalo/dashboard/chat/ZaloEmptyChat.tsx && echo "OK: ZaloEmptyChat.tsx (theirs)"
git checkout --ours linkedin-crawler-ui/components/facebook-crawler/modules/facebook-crawl/components/login.tsx && git add linkedin-crawler-ui/components/facebook-crawler/modules/facebook-crawl/components/login.tsx && echo "OK: login.tsx (ours)"
git checkout --ours linkedin-crawler-ui/components/facebook-crawler/modules/facebook-crawl/components/select-preset-groups-modal.tsx && git add linkedin-crawler-ui/components/facebook-crawler/modules/facebook-crawl/components/select-preset-groups-modal.tsx && echo "OK: select-preset-groups-modal.tsx (ours)"

echo ""
echo "=== Remaining ambiguous files - using THEIRS ==="
git checkout --theirs .gitignore && git add .gitignore && echo "OK: .gitignore (theirs)"
git checkout --theirs linkedin_group_crawler/.dockerignore && git add linkedin_group_crawler/.dockerignore && echo "OK: .dockerignore (theirs)"
git checkout --theirs linkedin_group_crawler/app/core/logger.py && git add linkedin_group_crawler/app/core/logger.py && echo "OK: logger.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/core/supabase_client.py && git add linkedin_group_crawler/app/core/supabase_client.py && echo "OK: supabase_client.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/main.py && git add linkedin_group_crawler/app/main.py && echo "OK: main.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/routers/admin_dashboard.py && git add linkedin_group_crawler/app/modules/all_platform/routers/admin_dashboard.py && echo "OK: admin_dashboard.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/routers/auth.py && git add linkedin_group_crawler/app/modules/all_platform/routers/auth.py && echo "OK: auth.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/routers/groups_linkedin.py && git add linkedin_group_crawler/app/modules/all_platform/routers/groups_linkedin.py && echo "OK: groups_linkedin.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/routers/social_accounts.py && git add linkedin_group_crawler/app/modules/all_platform/routers/social_accounts.py && echo "OK: social_accounts.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/services/admin_dashboard_service.py && git add linkedin_group_crawler/app/modules/all_platform/services/admin_dashboard_service.py && echo "OK: admin_dashboard_service.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/services/auth_service.py && git add linkedin_group_crawler/app/modules/all_platform/services/auth_service.py && echo "OK: auth_service.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/services/social_accounts_service.py && git add linkedin_group_crawler/app/modules/all_platform/services/social_accounts_service.py && echo "OK: social_accounts_service.py (theirs)"
git checkout --theirs linkedin_group_crawler/app/modules/all_platform/services/supabase_user_service.py && git add linkedin_group_crawler/app/modules/all_platform/services/supabase_user_service.py && echo "OK: supabase_user_service.py (theirs)"
git checkout --ours linkedin_group_crawler/app/modules/all_platform/routers/fb.py && git add linkedin_group_crawler/app/modules/all_platform/routers/fb.py && echo "OK: fb.py (ours)"

echo ""
echo "=== UI remaining files ==="
git checkout --theirs linkedin-crawler-ui/app/(all-platform)/all-platform/admin/dashboard/page.tsx && git add linkedin-crawler-ui/app/(all-platform)/all-platform/admin/dashboard/page.tsx && echo "OK: admin/dashboard (theirs)"
git checkout --ours linkedin-crawler-ui/app/(all-platform)/all-platform/inbox/page.tsx && git add linkedin-crawler-ui/app/(all-platform)/all-platform/inbox/page.tsx && echo "OK: inbox/page.tsx (ours)"
git checkout --theirs linkedin-crawler-ui/app/(all-platform-chat)/layout.tsx && git add linkedin-crawler-ui/app/(all-platform-chat)/layout.tsx && echo "OK: (all-platform-chat)/layout.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/app/(all-platform-chat)/zalo-chat/page.tsx && git add linkedin-crawler-ui/app/(all-platform-chat)/zalo-chat/page.tsx && echo "OK: zalo-chat/page.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/app/globals.css && git add linkedin-crawler-ui/app/globals.css && echo "OK: globals.css (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/category-management.tsx && git add linkedin-crawler-ui/components/all-platform/category-management.tsx && echo "OK: category-management.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/components/seeding-modal.tsx && git add linkedin-crawler-ui/components/all-platform/components/seeding-modal.tsx && echo "OK: seeding-modal.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/all-platform/layout/AllPlatformShell.tsx && git add linkedin-crawler-ui/components/all-platform/layout/AllPlatformShell.tsx && echo "OK: AllPlatformShell.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/features/auth/ForbiddenPage.tsx && git add linkedin-crawler-ui/components/features/auth/ForbiddenPage.tsx && echo "OK: ForbiddenPage.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/features/dashboard/CategoryManagementContent.tsx && git add linkedin-crawler-ui/components/features/dashboard/CategoryManagementContent.tsx && echo "OK: CategoryManagementContent.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/components/ui/MaterialIcon.tsx && git add linkedin-crawler-ui/components/ui/MaterialIcon.tsx && echo "OK: MaterialIcon.tsx (theirs)"
git checkout --theirs linkedin-crawler-ui/services/all-platform.service.ts && git add linkedin-crawler-ui/services/all-platform.service.ts && echo "OK: all-platform.service.ts (theirs)"
git checkout --ours linkedin-crawler-ui/public/markee-extension.zip && git add linkedin-crawler-ui/public/markee-extension.zip && echo "OK: markee-extension.zip (ours)"

echo ""
echo "=== Done. Remaining conflicts: ==="
git status --short | grep -E "^(UU|AU|DD|AA|UU)" | head -20
