-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.seeding_content_kpi (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid NOT NULL,
  link_comment text UNIQUE,
  content text,
  link_post text NOT NULL,
  verify text DEFAULT 'pending'::text CHECK (verify = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  current_day date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id_social_account uuid,
  id_platform bigint,
  id_post uuid,
  CONSTRAINT seeding_content_kpi_pkey PRIMARY KEY (id),
  CONSTRAINT fk_seeding_content_kpi_member FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT fk_seeding_kpi_social_account FOREIGN KEY (id_social_account) REFERENCES public.social_accounts(id),
  CONSTRAINT fk_seeding_kpi_platform FOREIGN KEY (id_platform) REFERENCES public.platforms(id)
);
CREATE TABLE public.kpi_tracker (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid NOT NULL,
  id_leader uuid NOT NULL,
  id_platform bigint NOT NULL,
  kpi_comment integer DEFAULT 0,
  start_date date,
  end_date date,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'pending'::text, 'completed'::text, 'Trễ deadline'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  kpi_inbox integer,
  kpi_post integer,
  kpi_lead integer,
  id_team uuid,
  is_failed boolean DEFAULT false,
  reason_not_met text,
  CONSTRAINT kpi_tracker_pkey PRIMARY KEY (id),
  CONSTRAINT kpi_tracker_id_teams_fkey FOREIGN KEY (id_team) REFERENCES public.teams(id),
  CONSTRAINT kpi_tracker_id_leader_fkey FOREIGN KEY (id_leader) REFERENCES public.app_users(id),
  CONSTRAINT kpi_tracker_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT kpi_tracker_id_platform_fkey FOREIGN KEY (id_platform) REFERENCES public.platforms(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_leader uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  name_team text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT fk_teams_leader FOREIGN KEY (id_leader) REFERENCES public.app_users(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_type text NOT NULL CHECK (category_type = ANY (ARRAY['intent'::text, 'industry'::text, 'tier'::text, 'team'::text, 'icp'::text, 'content_type'::text, 'product_seeding'::text])),
  code text NOT NULL,
  name text,
  description text,
  platform text DEFAULT 'general'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.linkedin_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  id_account_crawl uuid NOT NULL,
  crawl_date date,
  post_url text NOT NULL UNIQUE,
  author text,
  content text,
  likes integer DEFAULT 0,
  comments integer DEFAULT 0,
  shares integer DEFAULT 0,
  score integer DEFAULT 0,
  posted_at timestamp with time zone,
  total_posts_per_run integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id_group uuid,
  id_member uuid,
  CONSTRAINT linkedin_posts_pkey PRIMARY KEY (id),
  CONSTRAINT linkedin_posts_id_account_crawl_fkey FOREIGN KEY (id_account_crawl) REFERENCES public.linkedin_account_crawl(id),
  CONSTRAINT linkedin_posts_id_group_fkey FOREIGN KEY (id_group) REFERENCES public.linkedin_groups(id),
  CONSTRAINT linkedin_posts_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT linkedin_posts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.crawl_linkedin_session(id)
);
CREATE TABLE public.linkedin_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_url text,
  group_name text,
  status text DEFAULT 'idle'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id_intent uuid DEFAULT gen_random_uuid(),
  id_industry uuid DEFAULT gen_random_uuid(),
  id_team uuid DEFAULT gen_random_uuid(),
  id_icp uuid DEFAULT gen_random_uuid(),
  id_tier uuid DEFAULT gen_random_uuid(),
  id_member uuid DEFAULT gen_random_uuid(),
  id_content_type uuid DEFAULT gen_random_uuid(),
  id_product_seeding uuid,
  assignee_id uuid,
  co_assignee_id uuid DEFAULT gen_random_uuid(),
  note text,
  risk_note text,
  CONSTRAINT linkedin_groups_pkey PRIMARY KEY (id),
  CONSTRAINT linkedin_groups_id_team_fkey FOREIGN KEY (id_team) REFERENCES public.teams(id),
  CONSTRAINT linkedin_groups_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT linkedin_groups_id_icp_fkey FOREIGN KEY (id_icp) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_id_industry_fkey FOREIGN KEY (id_industry) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_id_intent_fkey FOREIGN KEY (id_intent) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_id_tier_fkey FOREIGN KEY (id_tier) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_id_content_type_fkey FOREIGN KEY (id_content_type) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_id_product_seeding_fkey FOREIGN KEY (id_product_seeding) REFERENCES public.categories(id),
  CONSTRAINT linkedin_groups_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.app_users(id),
  CONSTRAINT linkedin_groups_co_assignee_id_fkey FOREIGN KEY (co_assignee_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.facebook_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_name text NOT NULL,
  group_url text,
  members integer,
  posts_per_week integer,
  health_score integer,
  chay_24h boolean DEFAULT false,
  last_crawl timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id_intent uuid,
  id_industry uuid,
  id_tier uuid,
  id_team uuid,
  id_icp uuid,
  id_member uuid DEFAULT gen_random_uuid(),
  crawl_time time without time zone,
  crawl_frequency character varying,
  start_time_in_day bigint,
  end_time_in_day bigint,
  time_crawl bigint,
  end_time_24h date,
  end_date_hour date,
  id_content_type uuid,
  id_product_seeding uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'paused'::text])),
  assignee_id uuid,
  risk_note text,
  note text,
  co_assignee_id uuid,
  CONSTRAINT facebook_groups_pkey PRIMARY KEY (id),
  CONSTRAINT facebook_groups_id_team_fkey FOREIGN KEY (id_team) REFERENCES public.teams(id),
  CONSTRAINT facebook_groups_id_icp_fkey FOREIGN KEY (id_icp) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_id_industry_fkey FOREIGN KEY (id_industry) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_id_intent_fkey FOREIGN KEY (id_intent) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_id_tier_fkey FOREIGN KEY (id_tier) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT facebook_groups_id_content_type_fkey FOREIGN KEY (id_content_type) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_id_product_seeding_fkey FOREIGN KEY (id_product_seeding) REFERENCES public.categories(id),
  CONSTRAINT facebook_groups_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.app_users(id),
  CONSTRAINT facebook_groups_co_assignee_id_fkey FOREIGN KEY (co_assignee_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.facebook_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_id uuid DEFAULT gen_random_uuid(),
  post_url text,
  crawl_date timestamp with time zone,
  post_time timestamp with time zone,
  content text,
  score integer DEFAULT 0,
  reactions integer DEFAULT 0,
  comments integer DEFAULT 0,
  shares integer DEFAULT 0,
  media_url text,
  image_urls ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id_member uuid DEFAULT gen_random_uuid(),
  id_author text,
  CONSTRAINT facebook_posts_pkey PRIMARY KEY (id),
  CONSTRAINT facebook_posts_id_author_fkey FOREIGN KEY (id_author) REFERENCES public.author_post(id),
  CONSTRAINT facebook_posts_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.facebook_groups(id),
  CONSTRAINT facebook_posts_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.crawl_linkedin_session (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_account_crawl uuid NOT NULL DEFAULT gen_random_uuid(),
  id_platform bigint NOT NULL,
  posts_count integer DEFAULT 0,
  status text DEFAULT 'completed'::text,
  created_at timestamp with time zone DEFAULT now(),
  id_member uuid DEFAULT gen_random_uuid(),
  CONSTRAINT crawl_linkedin_session_pkey PRIMARY KEY (id),
  CONSTRAINT crawl_linkedin_session_id_platform_fkey FOREIGN KEY (id_platform) REFERENCES public.platforms(id),
  CONSTRAINT crawl_linkedin_session_id_account_crawl_fkey FOREIGN KEY (id_account_crawl) REFERENCES public.linkedin_account_crawl(id),
  CONSTRAINT crawl_linkedin_session_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.facebook_accounts_crawl (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password text,
  two_fa text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT facebook_accounts_crawl_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  name text,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['member'::text, 'leader'::text, 'admin'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_user_id uuid NOT NULL,
  account_name text NOT NULL,
  account_email text,
  account_password text,
  is_active boolean NOT NULL DEFAULT true,
  is_primary boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  account_profile_id text,
  id_platform bigint,
  is_banned boolean DEFAULT false,
  ban_reason text,
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_accounts_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id),
  CONSTRAINT social_accounts_id_platform_fkey FOREIGN KEY (id_platform) REFERENCES public.platforms(id),
  CONSTRAINT fk_id_platform FOREIGN KEY (id_platform) REFERENCES public.platforms(id)
);
CREATE TABLE public.leader_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leader_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.linkedin_account_crawl (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid DEFAULT gen_random_uuid(),
  email_linkedin text,
  password text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  phone text,
  CONSTRAINT linkedin_account_crawl_pkey PRIMARY KEY (id),
  CONSTRAINT linkedin_account_crawl_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.account_crawl (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  id_member uuid,
  email text,
  phone_number text,
  password text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT account_crawl_pkey PRIMARY KEY (id),
  CONSTRAINT account_crawl_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.platforms (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  CONSTRAINT platforms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.member_of_teams (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_member uuid DEFAULT gen_random_uuid(),
  id_teams uuid DEFAULT gen_random_uuid(),
  CONSTRAINT member_of_teams_pkey PRIMARY KEY (id),
  CONSTRAINT member_of_teams_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT member_of_teams_id_teams_fkey FOREIGN KEY (id_teams) REFERENCES public.teams(id)
);
CREATE TABLE public.zalo_users (
  user_id text NOT NULL,
  display_name text,
  zalo_status text NOT NULL DEFAULT 'unknown'::text,
  last_login_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  assigned_worker_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cookie text,
  id_member uuid DEFAULT gen_random_uuid(),
  CONSTRAINT zalo_users_pkey PRIMARY KEY (user_id),
  CONSTRAINT zalo_users_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.zalo_accounts (
  account_id text NOT NULL,
  owner_id text NOT NULL DEFAULT 'default'::text,
  label text NOT NULL,
  phone text,
  zalo_id text,
  avatar_url text,
  status text NOT NULL DEFAULT 'unknown'::text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id_member uuid DEFAULT gen_random_uuid(),
  CONSTRAINT zalo_accounts_pkey PRIMARY KEY (account_id),
  CONSTRAINT zalo_accounts_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.zalo_crawl_jobs (
  job_id text NOT NULL,
  user_id text NOT NULL,
  group_id text,
  group_name text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text,
  messages_collected integer NOT NULL DEFAULT 0,
  images_found integer NOT NULL DEFAULT 0,
  oldest_message_date text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_crawl_jobs_pkey PRIMARY KEY (job_id)
);
CREATE TABLE public.zalo_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  group_id text NOT NULL,
  group_name text NOT NULL,
  avatar_url text,
  unread_count integer DEFAULT 0,
  last_message_at timestamp with time zone,
  last_message_content text,
  last_sender_id text,
  last_sender_name text,
  last_message_type text,
  is_pinned boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_friend boolean DEFAULT false,
  CONSTRAINT zalo_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zalo_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  job_id text,
  group_id text,
  group_name text,
  source_message_id text,
  sender_id text,
  sender_name text,
  timestamp_text text,
  time_text text,
  type text NOT NULL DEFAULT 'text'::text,
  content text,
  is_sent boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_messages_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_messages_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.zalo_crawl_jobs(job_id)
);
CREATE TABLE public.zalo_message_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  source_url text,
  storage_path text,
  storage_url text,
  status text NOT NULL DEFAULT 'pending'::text,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_message_assets_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_message_assets_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.zalo_messages(id)
);
CREATE TABLE public.zalo_broadcast_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text,
  content_mode text NOT NULL DEFAULT 'both'::text,
  message_count integer NOT NULL DEFAULT 0,
  target_count integer NOT NULL DEFAULT 0,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT zalo_broadcast_campaigns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zalo_broadcast_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  group_id text,
  group_name text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_broadcast_targets_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_broadcast_targets_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.zalo_broadcast_campaigns(id)
);
CREATE TABLE public.zalo_broadcast_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  message_id uuid NOT NULL,
  position integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'queued'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_broadcast_items_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_broadcast_items_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.zalo_broadcast_campaigns(id),
  CONSTRAINT zalo_broadcast_items_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.zalo_messages(id)
);
CREATE TABLE public.zalo_broadcast_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  group_name text NOT NULL DEFAULT ''::text,
  message_id uuid,
  status text NOT NULL,
  detail text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zalo_broadcast_logs_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_broadcast_logs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.zalo_broadcast_campaigns(id),
  CONSTRAINT zalo_broadcast_logs_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.zalo_messages(id)
);
CREATE TABLE public.zalo_conversation_permissions (
  id bigint NOT NULL DEFAULT nextval('zalo_conversation_permissions_id_seq'::regclass),
  account_id text NOT NULL,
  conversation_id text NOT NULL UNIQUE,
  shared_role text NOT NULL DEFAULT 'admin'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id_member uuid,
  id_leader uuid,
  note text,
  verified_at timestamp with time zone,
  verified_by uuid,
  is_verify boolean,
  is_lead boolean,
  CONSTRAINT zalo_conversation_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT zalo_conversation_permissions_id_leader_fkey FOREIGN KEY (id_leader) REFERENCES public.app_users(id),
  CONSTRAINT zalo_conversation_permissions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.app_users(id),
  CONSTRAINT fk_zalo_conv_perm_account FOREIGN KEY (account_id) REFERENCES public.zalo_accounts(account_id)
);
CREATE TABLE public.Vps_cookies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vps_fb_id bigint,
  cookie json,
  last_used_at timestamp with time zone,
  cooldown_until timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED DEFAULT 'idle'::cookie_status,
  error_reason text,
  email text,
  id_member uuid,
  CONSTRAINT Vps_cookies_pkey PRIMARY KEY (id),
  CONSTRAINT Vps_cookies_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT vps_cookies_vps_fb_id_fkey FOREIGN KEY (vps_fb_id) REFERENCES public.Vps_fb1(id)
);
CREATE TABLE public.Vps_fb1 (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  http text,
  active_session bigint DEFAULT '0'::bigint,
  active boolean DEFAULT false,
  CONSTRAINT Vps_fb1_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fb_inbox_kpi (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid NOT NULL,
  id_leader uuid NOT NULL,
  conv_id text NOT NULL,
  user_id text NOT NULL,
  message_count integer NOT NULL DEFAULT 1,
  is_lead boolean NOT NULL DEFAULT false,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_confirmed boolean NOT NULL DEFAULT false,
  CONSTRAINT fb_inbox_kpi_pkey PRIMARY KEY (id),
  CONSTRAINT fb_inbox_kpi_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT fb_inbox_kpi_id_leader_fkey FOREIGN KEY (id_leader) REFERENCES public.app_users(id)
);
CREATE TABLE public.fb_inbox_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid NOT NULL,
  user_id text NOT NULL UNIQUE,
  fb_user_id text,
  account_label text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fb_inbox_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT fb_inbox_accounts_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.fb_post_kpi (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid NOT NULL,
  id_leader uuid NOT NULL,
  user_id text NOT NULL,
  job_id text NOT NULL UNIQUE,
  post_url text,
  content text,
  target_type text DEFAULT 'profile'::text,
  target_id text,
  platform text DEFAULT 'facebook'::text,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fb_post_kpi_pkey PRIMARY KEY (id),
  CONSTRAINT fb_post_kpi_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id),
  CONSTRAINT fb_post_kpi_id_leader_fkey FOREIGN KEY (id_leader) REFERENCES public.app_users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id text NOT NULL,
  conversation_id text NOT NULL,
  conversation_type text NOT NULL DEFAULT 'group'::text CHECK (conversation_type = ANY (ARRAY['user'::text, 'group'::text])),
  display_name text NOT NULL,
  avatar_url text,
  last_message_id text,
  last_message_content text,
  last_message_type text,
  last_message_time timestamp with time zone,
  last_sender_id text,
  last_sender_name text,
  unread_count integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
  is_pinned boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  is_muted boolean NOT NULL DEFAULT false,
  sync_status text NOT NULL DEFAULT 'known'::text,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.author_post (
  id text NOT NULL DEFAULT 'NULL'::text,
  create_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  url_profile text,
  CONSTRAINT author_post_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_name text NOT NULL,
  company_name text,
  leaded_by uuid,
  is_assigned boolean DEFAULT false,
  sdr_id uuid,
  conv_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'closed'::text, 'rejected'::text])),
  note text,
  reject_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phone text,
  email text,
  address text,
  city text,
  website text,
  industry text,
  tax_code text,
  source_platform text DEFAULT 'FB_Inbox'::text CHECK (source_platform = ANY (ARRAY['Manual'::text, 'FB_Inbox'::text, 'FB_Group'::text, 'Zalo'::text, 'Website'::text, 'Referral'::text, 'MarkeeChat'::text])),
  customer_since timestamp with time zone,
  service_package text,
  lifetime_value numeric DEFAULT 0,
  contract_signed_at timestamp with time zone,
  contract_status text DEFAULT 'active'::text CHECK (contract_status = ANY (ARRAY['active'::text, 'completed'::text, 'maintenance'::text])),
  warranty_expires_at timestamp with time zone,
  care_note text,
  last_care_at timestamp with time zone,
  tags ARRAY DEFAULT '{}'::text[],
  activity_status text DEFAULT 'active'::text CHECK (activity_status = ANY (ARRAY['active'::text, 'paused'::text, 'churned'::text])),
  has_budget boolean DEFAULT false,
  reject_reason_type text CHECK (reject_reason_type = ANY (ARRAY['Khong_lien_lac_duoc'::text, 'Chua_co_nhu_cau'::text, 'Cham_trai_nghiem'::text, 'Thieu_nhan_su'::text, 'Chia_tay_doi_tac_cu'::text, 'Khong_du_tai_chinh'::text, 'Chua_phu_hop_thoi_diem'::text, 'Khac'::text])),
  review_result text CHECK (review_result = ANY (ARRAY['Qualify'::text, 'Disqualify'::text, 'Chua_xem_xet'::text])),
  deal_stage text DEFAULT 'new_lead'::text CHECK (deal_stage = ANY (ARRAY['new_lead'::text, 'contacted'::text, 'qualified'::text, 'requirement'::text, 'proposal_sent'::text, 'negotiation'::text, 'contract_sent'::text, 'on_hold'::text, 'won'::text, 'lost'::text])),
  prev_stage text,
  follow_up_date timestamp with time zone,
  decision_maker text,
  estimated_budget numeric DEFAULT 0,
  stage_entered_at timestamp with time zone DEFAULT now(),
  last_attachment_url text,
  last_attachment_name text,
  closed_reason text,
  payment_due_date timestamp with time zone,
  payment_status text DEFAULT 'unpaid'::text CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text])),
  quote_id uuid,
  CONSTRAINT customer_leads_pkey PRIMARY KEY (id),
  CONSTRAINT customer_leads_leaded_by_fkey FOREIGN KEY (leaded_by) REFERENCES public.app_users(id),
  CONSTRAINT customer_leads_sdr_id_fkey FOREIGN KEY (sdr_id) REFERENCES public.app_users(id),
  CONSTRAINT customer_leads_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.vps (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ip text NOT NULL,
  password text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_member uuid,
  port bigint,
  display_name text,
  vps_protocol_enum USER-DEFINED DEFAULT 'vnc'::vps_protocol_enum,
  Username text,
  CONSTRAINT vps_pkey PRIMARY KEY (id),
  CONSTRAINT vps_id_member_fkey FOREIGN KEY (id_member) REFERENCES public.app_users(id)
);
CREATE TABLE public.customer_lead_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  action text NOT NULL,
  from_stage text,
  to_stage text,
  field text,
  old_value text,
  new_value text,
  actor_id uuid,
  actor_name text,
  note text,
  attachment_url text,
  attachment_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_lead_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT customer_lead_activity_log_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_leads(id)
);
CREATE TABLE public.inbox_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  label text NOT NULL,
  content text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  order_index integer NOT NULL DEFAULT 0,
  CONSTRAINT inbox_templates_pkey PRIMARY KEY (id),
  CONSTRAINT inbox_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.crawl_workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id text NOT NULL UNIQUE,
  name text,
  status text NOT NULL DEFAULT 'offline'::text CHECK (status = ANY (ARRAY['idle'::text, 'busy'::text, 'offline'::text])),
  current_job_id uuid,
  last_heartbeat timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crawl_workers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crawl_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform text NOT NULL DEFAULT 'facebook'::text CHECK (platform = ANY (ARRAY['facebook'::text, 'linkedin'::text])),
  group_url text NOT NULL,
  group_name text,
  group_id uuid,
  id_member uuid,
  keywords jsonb,
  post_limit integer,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'assigned'::text, 'processing'::text, 'done'::text, 'failed'::text])),
  assigned_worker_id text,
  result_count integer,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT crawl_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quote_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  schema_version integer NOT NULL DEFAULT 1,
  layout_type text NOT NULL DEFAULT 'cloudgate_standard_quote'::text,
  schema_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  share_token text,
  share_enabled boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_forms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  deal_id uuid,
  quote_form_id uuid NOT NULL,
  quote_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'cancelled'::text])),
  form_schema_version integer NOT NULL,
  form_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  subtotal_amount numeric NOT NULL DEFAULT 0,
  vat_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'VND'::text,
  issued_at timestamp with time zone,
  valid_until timestamp with time zone,
  public_token text,
  public_enabled boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.customer_leads(id),
  CONSTRAINT quotes_quote_form_id_fkey FOREIGN KEY (quote_form_id) REFERENCES public.quote_forms(id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.quote_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  quote_id uuid NOT NULL,
  description text NOT NULL,
  unit text,
  quantity numeric NOT NULL DEFAULT 0,
  unit_price numeric NOT NULL DEFAULT 0,
  vat_rate numeric NOT NULL DEFAULT 0,
  subtotal_amount numeric NOT NULL DEFAULT 0,
  vat_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT quote_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.sales_assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text NOT NULL CHECK (type = ANY (ARRAY['proposal'::text, 'sale_kit'::text, 'portfolio'::text, 'other'::text, 'brochure'::text, 'case_study'::text, 'company_profile'::text])),
  title text NOT NULL,
  description text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  industry text,
  service_package text,
  file_url text,
  public_url text,
  thumbnail_url text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  archived_at timestamp with time zone,
  customer_lead_id uuid,
  deal_id uuid,
  project_name text,
  version text,
  source_type text CHECK (source_type IS NULL OR (source_type = ANY (ARRAY['canva'::text, 'google_docs'::text, 'google_drive'::text, 'external'::text]))),
  source_url text,
  CONSTRAINT sales_assets_pkey PRIMARY KEY (id),
  CONSTRAINT sales_assets_customer_lead_id_fkey FOREIGN KEY (customer_lead_id) REFERENCES public.customer_leads(id),
  CONSTRAINT sales_assets_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.customer_leads(id),
  CONSTRAINT sales_assets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.kpi_reward_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  metric text NOT NULL CHECK (metric = ANY (ARRAY['lead'::text, 'inbox'::text, 'post'::text, 'comment'::text, 'total_bonus'::text])),
  weight numeric NOT NULL DEFAULT 1,
  threshold_value numeric NOT NULL DEFAULT 0,
  reward_per_unit numeric NOT NULL DEFAULT 0,
  max_reward numeric,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'rejected'::text])),
  leader_note text,
  admin_note text,
  created_by uuid,
  submitted_by uuid,
  reviewed_by uuid,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  max_rate numeric NOT NULL DEFAULT 200,
  CONSTRAINT kpi_reward_rules_pkey PRIMARY KEY (id),
  CONSTRAINT kpi_reward_rules_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT kpi_reward_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id),
  CONSTRAINT kpi_reward_rules_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.app_users(id),
  CONSTRAINT kpi_reward_rules_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.kpi_reward_rule_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  changed_by uuid,
  changed_by_name text,
  changed_by_email text,
  changes jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kpi_reward_rule_logs_pkey PRIMARY KEY (id)
);